params:
 test: teconfig_pathstKeyword
 epochs: 30
 batch_size: 32
 no_classes: 10
 input_shape: [28,28]
 loss_function: sparse_categorical_crossentropy
 metrics: accuracy
 optimizer: SGD
 validation_datasize: 5000

artifacts:
 artifacts_dir: artifacts
 model_dr: model_dr
 plots_dr: plots_
 checkpoint_dr: checkpoints

logs: 
 logs_dir: logs_dir
 general_logs: general_logs
 tensorboard_logs: tensorboard_logs